import { ROLES, type Role } from "./roles";

export const PERMISSIONS = {
  PROJECT_CREATE: "project.create",
  PROJECT_READ: "project.read",
  PROJECT_UPDATE: "project.update",
  PROJECT_DELETE: "project.delete",

  REPORTS_READ: "reports.read",
  REPORTS_EXPORT: "reports.export",

  USERS_READ: "users.read",
  USERS_MANAGE: "users.manage",

  ORG_SETTINGS_MANAGE: "org.settings.manage",

  MEMBERS_READ: "members.read",
  MEMBERS_MANAGE: "members.manage",

  CONTRIBUTIONS_READ: "contributions.read",
  CONTRIBUTIONS_MANAGE: "contributions.manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ORG_SETTINGS_MANAGE,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.MEMBERS_MANAGE,
    PERMISSIONS.CONTRIBUTIONS_READ,
    PERMISSIONS.CONTRIBUTIONS_MANAGE,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.MEMBERS_MANAGE,
    PERMISSIONS.CONTRIBUTIONS_READ,
    PERMISSIONS.CONTRIBUTIONS_MANAGE,
  ],
  [ROLES.CASHIER]: [
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.CONTRIBUTIONS_READ,
    PERMISSIONS.CONTRIBUTIONS_MANAGE,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.CONTRIBUTIONS_READ,
  ],
};

export function hasPermission(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}
