import { ROLES, type Role } from "./roles";

export const PERMISSIONS = {
  TRANSACTION_CREATE: "transaction.create",
  TRANSACTION_READ: "transaction.read",
  TRANSACTION_UPDATE: "transaction.update",
  TRANSACTION_DELETE: "transaction.delete",

  PROJECT_CREATE: "project.create",
  PROJECT_READ: "project.read",
  PROJECT_UPDATE: "project.update",
  PROJECT_DELETE: "project.delete",

  REPORTS_READ: "reports.read",
  REPORTS_EXPORT: "reports.export",

  USERS_READ: "users.read",
  USERS_MANAGE: "users.manage",

  ORG_SETTINGS_MANAGE: "org.settings.manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.TRANSACTION_CREATE,
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.TRANSACTION_UPDATE,
    PERMISSIONS.TRANSACTION_DELETE,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ORG_SETTINGS_MANAGE,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.TRANSACTION_CREATE,
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.TRANSACTION_UPDATE,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.USERS_READ,
  ],
  [ROLES.CASHIER]: [
    PERMISSIONS.TRANSACTION_CREATE,
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.REPORTS_READ,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.REPORTS_READ,
  ],
};

export function hasPermission(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}
